server:
  port: 8889

spring:
  application:
    name: service-hello

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"